project:
  namespace: "org.simplemodeling.textus"
  id: "Bok"
  name: "textus-bok"
  title: "Textus BoK"
  kind: car
  scalaPackage: "org.simplemodeling.textus.bok"
  component:
    name: "Bok"
    className: "BokComponent"
    displayName: "Textus BoK"
    version: "0.1.0-SNAPSHOT"
    config:
      textus.server.default-port: "18014"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.4-SNAPSHOT"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.2-SNAPSHOT"
    provided:
      - "org.simplemodeling.textus::textus-semantic-integration-engine:0.2.0-SNAPSHOT"
    test:
      - "org.scalatest::scalatest:3.2.19"
      - "org.textus::textus-scraper:0.1.1-SNAPSHOT"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    abi:
      dependencies:
        - namespace: "org.simplemodeling.textus"
          id: "SemanticIntegrationEngine"
          abiRange: "[0.2.0,0.3.0)"
    manifest_metadata:
      boundedContext: "body-of-knowledge"
      domain: "bok"
    runtime:
      cncf:
        minimum: "0.5.2-SNAPSHOT"
        excluded: []
        tested:
          - "0.5.2-SNAPSHOT"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-bok"
